apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://host.docker.internal:8087
    database: 'solarautopilot'
    jsonData:
      httpMode: GET
      timeInterval: "1s"
