apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: 'solarautopilot'
    user: 'solaruser'
    password: 'solarpass123'
    jsonData:
      httpMode: GET
      timeInterval: "1s" 
